Add docs for creating custom lemmy frontend
LemmyNet/lemmy pull request #1319
Opened 2020-12-15 16:26 UTC by Nutomic

I think there is a lot of potential with custom frontends for Lemmy, so I decided to write a guide. 

@IronOxidizer Please have a look and tell me if anything is missing.

2020-12-15 16:28 UTC, Nutomic commented on docs/src/contributing/custom_frontend.md
> +```
@dessalines this is probably incomplete

2020-12-15 22:48 UTC, dessalines commented on docs/src/contributing/custom_frontend.md
> +To test, follow the [local development instructions](local_development.md) (you only need the database and backend dependencies). Then do `cargo run` in the Lemmy repo. Start your frontend, using `lo
Here I would link to docker development instead... it does run the lemmy-ui (which would be unecessary for someone developing an alternate front end), but it also sets up pictrs and iframely too, which alternate front ends might need to make sure images are being rendered.

2020-12-15 22:49 UTC, dessalines commented on docs/src/contributing/custom_frontend.md
> +The next step is building a Docker image from your frontend. If you forked an existing project, it should already include a `Dockerfile` and instructions to build it. Otherwise, try searching for you
Add a space after this line, I've seen issues with commonmark without it.

2020-12-15 22:52 UTC, dessalines commented on docs/src/contributing/custom_frontend.md
> +```
Just add these two lines to the bottom.

```
let headers = setForwardedHeaders(req.headers);
let client = new LemmyHttp(httpUri, headers);
```

2020-12-15 22:53 UTC, dessalines requested changes
Just those above.

2020-12-16 13:18 UTC, Nutomic commented
Updated and force pushed with your suggestions @dessalines. I also extended the introduction a bit.

2020-12-16 14:03 UTC, dessalines commented
Looks good to me.

2020-12-16 14:03 UTC, merged