Add option to limit community creation to admins only (fixes #1586)
LemmyNet/lemmy pull request #1587
Opened 2021-04-20 15:54 UTC by Nutomic

Quite easy to implement, and its something that has been requested a lot. Maybe the variable could have a better name.

2021-04-21 14:09 UTC, dessalines requested changes

2021-04-21 14:09 UTC, dessalines commented on crates/api_common/src/site.rs
> +  pub community_creation_admin_only: bool,
Order doesn't matter here, could you move this above auth.

2021-04-21 14:09 UTC, dessalines commented on crates/api_common/src/site.rs
> +  pub community_creation_admin_only: Option<bool>,
Same.

2021-04-21 14:09 UTC, dessalines commented on crates/api_crud/src/community/create.rs
> +      return Err(ApiError::err("only_admins_can_create_communities").into());
I'll add this to lemmy-translations

2021-04-21 14:09 UTC, dessalines commented on crates/api_common/src/site.rs
> +  pub community_creation_admin_only: bool,
Side point, but since all of these have defaults, I can probably make them optional.

2021-04-22 11:59 UTC, Nutomic commented
Updated.

2021-04-22 23:42 UTC, merged