Adding a vector indexing check to prevent panics. Fixes #2753
LemmyNet/lemmy pull request #2754
Opened 2023-02-22 14:43 UTC by dessalines

This **should** fail at the moment, since it should find a lot of these.

2023-02-23 02:52 UTC, Nutomic commented
You should put it in the second clippy line so that it doesnt apply to tests. And probably need to remove it from fix-clippy.sh then.

2023-02-23 14:49 UTC, dessalines commented
I'll work on this a little today.

I'll keep it in tests, I'll just do `.get(index).unwrap()`, because unwrap is good for tests.

> And probably need to remove it from fix-clippy.sh then.

We should probably keep the fix-clippy, and drone clippy check identical. Don't worry, I'll get this passing.

2023-02-24 07:58 UTC, Nutomic commented on crates/api/src/community/transfer.rs
> +        .unwrap_or(PersonId(0))
This makes the code unreadable. Store it in a variable first or make a helper method.

2023-02-24 08:04 UTC, Nutomic requested changes

2023-02-24 08:04 UTC, Nutomic commented on crates/apub/src/collections/community_featured.rs
> +        .expect("limiting the community post count")
I thought this was a false positive but it actually panicks. But use `unwrap_or_default()`.

2023-02-24 08:07 UTC, Nutomic commented
Would be nice if there was a clippy group to enable all lints regarding panicks at once.

I dont think this lint can be fixed automatically by clippy, right? So adding it to fix-clippy doesnt make much sense. Equally it doesnt make sense to apply this lint for tests, there are already too many unwraps. I would revert test changes and have the lint not run on test code (like drone does for unwrap). fix-clippy.sh can also run this and the unwrap check in a separate command so it ignores tests.

2023-02-28 11:34 UTC, Nutomic approved these changes

2023-02-28 11:34 UTC, merged