feat: use dotenv
LemmyNet/lemmy pull request #2761
Opened 2023-02-23 15:50 UTC by kulame

dotenv support

2023-02-23 19:47 UTC, dessalines requested changes

2023-02-23 19:47 UTC, dessalines commented on .env.test
> +LEMMY_DATABASE_URL="postgresql://dbuser:dbuser@localhost:5432/lemmy"
Could you remove this file? Thx.

2023-02-23 23:43 UTC, kulame commented on .env.test
> +LEMMY_DATABASE_URL="postgresql://dbuser:dbuser@localhost:5432/lemmy"
Already deleted.

2023-02-24 04:04 UTC, Nutomic commented
Whats the purpose of this change? You can already set the database url via env var or config file. Adding another way to set it would only cause confusion.

2023-02-24 08:46 UTC, kulame commented
> 

It is difficult to modify the system environment variables in some execution environments, and using dotenv as a replacement is a convenient way

2023-02-24 09:04 UTC, Nutomic commented
You should give more details what problem you are trying to solve like this, and why the config file is not sufficient. Keep in mind that we will have to support this functionality forever if it gets merged, so there needs to be a good reason.

2023-02-24 13:34 UTC, dessalines commented
I checked the docs, its just that line. I'm not exactly sure why you'd need a `.env` file in addition to the already externalized `lemmy.hjson` file tho.

2023-04-05 20:50 UTC, dessalines commented
We can probably close this, since the `lemmy.hjson` should be enough.

2023-04-05 20:50 UTC, closed without merging