Fix #2910 person aggregate count
LemmyNet/lemmy pull request #3047
Opened 2023-06-12 19:20 UTC by mikeyd85

I've fixed the issue whereby a user score will always get set to 0 regardless of the actual count. The performance should be improved now too as we are only calculating the user required, not all users, prior to the update.

2023-06-12 21:16 UTC, Nutomic commented
If you edit an old migration it will only help newly installed instances. You will have to generate a new migration to fix it for everyone.

2023-06-12 22:50 UTC, mikeyd85 commented
Oh, I see. I'm not sure how you'd do that @Nutomic .

2023-06-13 10:43 UTC, Nutomic commented
http://diesel.rs/guides/getting-started.html

2023-06-13 11:47 UTC, dessalines requested changes
Correct, do not edit old migrations, or they will break installations. Generate a new one and replace that function / trigger.

2023-07-10 18:57 UTC, dessalines commented
Has been fixed in a later PR.

2023-07-10 18:57 UTC, closed without merging