Allow passing command line params via environment (fixes #4603)
LemmyNet/lemmy pull request #4729
Opened 2024-05-21 10:41 UTC by Nutomic

[Described here](https://stackoverflow.com/a/73531388)

2024-05-21 13:22 UTC, dullbananas requested changes
Add "lemmy" prefix to env var names so they are consistent with existing environment variables (e.g. `env = "LEMMY_FOO"`)

2024-05-21 18:50 UTC, dessalines commented on src/lib.rs
> +  #[arg(long, env, default_value_t = false)]
looks like its as simple as adding `env = LEMMY_DISABLE_SCHEDULED_TASKS`

2024-05-22 08:24 UTC, Nutomic commented on src/lib.rs
> +  #[arg(long, env, default_value_t = false)]
Done

2024-05-22 12:21 UTC, SleeplessOne1917 approved these changes

2024-05-22 12:27 UTC, dessalines approved these changes

2024-05-22 12:37 UTC, dullbananas approved these changes

2024-05-22 12:39 UTC, merged