Adding a show_read override to GetPosts.
LemmyNet/lemmy pull request #4846
Opened 2024-06-18 17:03 UTC by dessalines

- If show_read is true, it overrides the local user show_read setting.
- Fixes #4124

2024-06-18 18:12 UTC, SleeplessOne1917 approved these changes

2024-06-18 18:24 UTC, dullbananas commented
`show_read: Some(false)` doesn't override the user setting, which could cause confusion. Use `Option<bool>` in `PostQuery`.

2024-06-18 20:28 UTC, dessalines commented
I've updated to make all of the post and comment query params as options.

2024-06-19 01:16 UTC, dullbananas requested changes
Changing to `Option<bool>` is not needed for fields other than `show_read` because they have the same default value every time, unlike `show_read` which overrides a `LocalUser` field.

If the inconsistency of using both `bool` and `Option<bool>` is a problem, then you can either:
* Keep these changes (except for the change to `page_back` in my opinion)
* Use `bool` instead of `Option<bool>`, remove the `Default` derive, and create this function that's does the same thing as `Default::default` except it sets `local_user: local_user, show_read: local_user.show_read_posts()`:
  ```
  fn new(local_user: Option<&'a LocalUser>) -> Self
  ```

2024-06-21 20:16 UTC, dessalines commented on crates/db_views/src/post_view.rs
> +    else if !(options.show_read.unwrap_or_default() || options.local_user.show_read_posts()) {
Thx, I've added this one, but I think I would like to keep these as Options.

2024-06-21 20:34 UTC, Nutomic approved these changes

2024-06-21 21:02 UTC, dullbananas approved these changes

2024-06-21 21:39 UTC, merged