Upgrading diesel and a few other deps.
LemmyNet/lemmy pull request #5203
Opened 2024-11-15 16:05 UTC by dessalines

2024-11-15 18:03 UTC, SleeplessOne1917 approved these changes

2024-11-15 23:50 UTC, dullbananas requested changes

2024-11-15 23:50 UTC, dullbananas commented on crates/db_schema/src/utils.rs
> +        Err(HookError::Message("Prevented first recycle".into()))
```suggestion
        Err(HookError::Message("Connection is too old".into()))
```

2024-11-18 08:33 UTC, Nutomic approved these changes

2024-11-18 17:23 UTC, dullbananas approved these changes

2024-11-18 17:23 UTC, merged