Feature filter keywords 3710
LemmyNet/lemmy pull request #5263
Opened 2024-12-14 14:41 UTC by leoseg

Option to block keyswords so no post containing this keywords in their name, body or url are returned, keywords are stored in seperate table related to person

2024-12-16 03:10 UTC, aeharding commented
What happens if you block "X"? Will it match "Xylophone"? What about "x.com"?

Unlike person and community blocks this seems a bit more ambiguous.

2024-12-16 08:39 UTC, leoseg commented
In the moment yes, because the ilike searches for case insensitive substrings.
 A possibility could be to block only posts and descriptions which containing the blocked keyword as one  word of his own (without being part of another word) , or urls having the keyword as parameter, or identifier without prefixes and suffices. For example for www.mcdonalds.com and the 'mcdonalds' part should be equal the blocked keyword if it should be filtered.

2024-12-17 09:50 UTC, Nutomic commented
You could also consider a minimum length of eg 3 characters for each blocked string.

2024-12-19 18:48 UTC, leoseg commented
yes this sounds more simple and in the Connect Lenny app they do it like this. I will add the restriction, fix checks add unit tests when I have time at the beginning of the next year.

2025-02-11 20:33 UTC, dessalines commented
I apologize for being slow to review this, ping me or request review when you'd like me to take a look.

2025-03-05 13:40 UTC, Nutomic commented on src/api_routes_v3.rs
> +            .route("/block", post().to(user_block_keyword_for_posts)),
Dont change api v3, this is only kept for backwards compatibility.

2025-03-05 13:40 UTC, Nutomic commented on src/api_routes_v4.rs
> +              .route("/post", post().to(user_block_keyword_for_posts)),
`/post_keywords`?

2025-03-05 13:41 UTC, Nutomic commented on migrations/2025-02-06-220512_update_keyword_length/up.sql
> +
There should only be a single migration per pull request. For the table name `user_post_keyword_block` is clearer.

2025-03-05 13:42 UTC, Nutomic commented on migrations/2024-12-29-203717_add_post_keyword_block_table/up.sql
> +);
Needs a unique constraint for `(keyword, person_id)`. You also might be able to use that as primary key and get rid of id.

2025-03-05 13:46 UTC, Nutomic commented on crates/db_schema/src/schema.rs
> +        #[max_length = 20]
This length doesnt match the migration.

2025-03-05 13:46 UTC, Nutomic commented on crates/db_schema/src/newtypes.rs
> +/// The comment reply id.
Wrong copypaste

2025-03-06 08:57 UTC, Nutomic commented on crates/db_views/src/post/post_view.rs
> +                ),
Instead of this raw sql you can build a regex like `(keyword1|keyword2|...)` and filter with that.

2025-03-10 09:41 UTC, leoseg commented on src/api_routes_v3.rs
> +            .route("/block", post().to(user_block_keyword_for_posts)),
I removed the changes

2025-03-10 09:41 UTC, leoseg commented on migrations/2025-02-06-220512_update_keyword_length/up.sql
> +
I deleted the new migration and altered the first migration.

2025-03-10 09:42 UTC, leoseg commented on migrations/2024-12-29-203717_add_post_keyword_block_table/up.sql
> +);
done

2025-03-10 09:42 UTC, leoseg commented on crates/db_schema/src/newtypes.rs
> +/// The comment reply id.
Is removed because id is replaced by compose primary key

2025-03-10 09:43 UTC, leoseg commented on crates/api/src/post/block.rs
> +}
Sounds good, should be more easy for the Frontend to implement, updated that this way.

2025-03-10 09:47 UTC, leoseg commented on crates/db_views/src/post/post_view.rs
> +                ),
I thought this would be less performant, as the regex string could be a bit long when there are for example 15 keywords? If i would do that would this be with like and than the regex `(keyword1|keyword2|...)` ?

2025-03-10 09:58 UTC, Nutomic commented on crates/db_views/src/post/post_view.rs
> +                ),
Not sure, cc @dessalines @dullbananas

2025-03-10 10:01 UTC, Nutomic commented on crates/db_schema/src/impls/post_keyword_block.rs
> +  }
This is only used in a test, you can replace it with `update()`. And the unblock method below is completely unused.

2025-03-10 14:13 UTC, dessalines commented on crates/db_views/src/post/post_view.rs
> +                ),
You should be able to use not similar to:

- https://docs.rs/diesel/latest/diesel/expression_methods/trait.PgTextExpressionMethods.html#method.not_similar_to
- https://stackoverflow.com/a/4928155/1655478

Regex would def be slower than this. But yeah none of this custom binding is necessary. Also extract the building of this string to its own function.

2025-03-10 14:13 UTC, dessalines commented on crates/utils/src/error.rs
> +  BlockKeywordLimitReached,
I don't think we need a limit, right?

2025-03-10 14:13 UTC, dessalines commented on crates/utils/src/error.rs
> +  BlockKeywordToShort,
`BlockKeywordTooShort`

2025-03-10 14:13 UTC, dessalines commented on crates/utils/src/error.rs
> +  BlockKeywordToLong,
`TooLong`

2025-03-10 14:13 UTC, dessalines commented on migrations/2024-12-29-203717_add_post_keyword_block_table/up.sql
> +CREATE TABLE user_post_keyword_block (
This table name doesn't look like any other one.

- Look at `local_user_language` for an example.
- It should be named `local_user_keyword_block` , as its a local user setting, not a person field that we need to worry about federation.
- Its columns should be `local_user_id, keyword` (in that order)
- I don't think we need to reference that this applies only to posts : `keyword_block` is enough. In the future we might want this to apply to comments and other things anyway.
- The performance of this scares me, and I don't think there's really a way we can make `lower(post.title) not similar to '%(keyword_1|keyword_2|...)%'` performant. But I'm still willing to merge it and hack on that later.

2025-03-10 14:13 UTC, dessalines commented on src/api_routes_v4.rs
> +              .route("/post_keywords", post().to(user_block_keyword_for_posts)),
This can be removed, as the keywords to block will be included as part of `save_user_settings`

2025-03-10 15:01 UTC, Nutomic commented on crates/db_schema/src/impls/post_keyword_block.rs
> +        Box::pin(async move {
No this should be fine, see https://github.com/LemmyNet/lemmy/pull/5480#issuecomment-2709050781

2025-03-11 00:08 UTC, dullbananas commented on crates/db_views/src/post/post_view.rs
> +                ),
Use this loop:

```
for keyword in blocked_keywords {
    let pattern = format!("%{}%", s);
    query = query.filter(post::name.not_like(pattern));
    query = query.filter(post::url.not_like(pattern));
    query = query.filter(post::body.not_like(pattern));
}
```

Also, it should probably be ilike instead of like

2025-03-11 01:26 UTC, dullbananas requested changes

2025-03-11 01:26 UTC, dullbananas commented on crates/db_schema/src/impls/post_keyword_block.rs
> +        Box::pin(async move {
Clarifying @Nutomic's comment: `.build_transaction().run(...)` must be changed to `.transaction(...)` to make it fine

2025-03-11 01:26 UTC, dullbananas commented on crates/api/src/post/block.rs
> +  }
This is how length is checked in other places, and this will also change the limit to 1000 which is good. The newly created error type must also be removed.

```suggestion
  if data.keywords_to_block.len() > MAX_API_PARAM_ELEMENTS {
    Err(LemmyErrorType::TooManyItems)?;
  }
```

2025-03-11 01:26 UTC, dullbananas commented on migrations/2024-12-29-203717_add_post_keyword_block_table/up.sql
> +CREATE TABLE user_post_keyword_block (
Also, "REFERENCES person" becomes "REFERENCES local_user"

2025-03-31 08:41 UTC, Nutomic commented on crates/db_schema/src/impls/keyword_block.rs
> +      .map(|keyword_block| keyword_block.keyword.clone())
Use into_iter() then no need for clone.

2025-03-31 08:43 UTC, Nutomic commented on crates/db_schema/src/impls/keyword_block.rs
> +            .do_nothing()
Is `on_conflict` really necessary considering that all values are deleted above?

2025-03-31 08:46 UTC, Nutomic commented on crates/db_views/src/post/post_view.rs
>            .await?;
Use `LocalUserKeywordBlock::read()`. For that you need to move the line `let conn = &mut get_conn(pool).await?;` down to the bottom of this function.

2025-03-31 08:47 UTC, Nutomic commented on crates/db_schema/src/impls/keyword_block.rs
> +          tokio::try_join!(delete_old, insert_new)?;
Dont use try_join, it will run delete and insert in parallel which causes problems. Instead run deletes first and inserts after, then no need for on conflict clause.

2025-03-31 08:49 UTC, Nutomic commented on crates/db_schema/src/impls/keyword_block.rs
> +            .do_nothing()
Should be enough with `on_conflict_do_nothing()`

2025-03-31 08:51 UTC, Nutomic commented on crates/utils/src/utils/validation.rs
> +  }
Use `max_length_check()` and `min_length_check()`

2025-03-31 08:51 UTC, Nutomic commented on crates/db_views/src/post/post_view.rs
> +  // }
Dont forget to enable this again

2025-04-01 15:44 UTC, dullbananas approved these changes

2025-04-03 09:31 UTC, Nutomic commented on crates/db_views/src/post/post_view.rs
> +  // }
Strange that it showed up in the diff.

2025-04-03 09:33 UTC, Nutomic commented on crates/api_common/src/post.rs
> +  pub keywords_to_block: Vec<String>,
This struct is now unused and can be removed. Otherwise looks ready to merge.

2025-04-03 12:17 UTC, Nutomic commented
See here in case you missed it: https://github.com/LemmyNet/lemmy/pull/5263/files#r2026591401

2025-04-03 14:07 UTC, leoseg commented
> See here in case you missed it: https://github.com/LemmyNet/lemmy/pull/5263/files#r2026591401
Ah Yes thanks, removed it now

2025-04-04 09:07 UTC, Nutomic approved these changes

2025-04-07 19:03 UTC, dessalines reviewed
@dullbananas should look at this also.

2025-04-07 19:03 UTC, dessalines commented on crates/db_views/src/post/post_view.rs
> +          }
The performance of this I'm sure is going to be awful, but we'll likely find that out later.

2025-04-07 20:48 UTC, dullbananas approved these changes

2025-04-08 07:39 UTC, Nutomic commented
Gonna merge this as its been open for a long time. We can make adjustments later if needed. Thanks for the contribution @leoseg!

2025-04-08 07:39 UTC, merged

2026-05-09 01:54 UTC, 621625 commented
Still can't see keyword block option on lemmy.world for example. What happened? Are we getting keyword blocks or not?

#Juvenile

2026-05-09 17:52 UTC, dessalines commented
Not released yet. It'll be in the 1.0 release.

2026-05-31 19:25 UTC, 621625 commented
> Not released yet. It'll be in the 1.0 release.

Yes, but when will v 1.0 be released? Reading lemmy without filters is hopeless. It causes brain rot. We need filters. Also a CLI similar to Reddio would be nice.

2026-05-31 19:43 UTC, Rikj000 commented
> Yes, but when will v 1.0 be released?

Check the `v1.0.0` milestone:
https://github.com/LemmyNet/lemmy/milestone/24

Don't ask deadlines for open source software, it will be ready, when it's ready.
If you want to see it happen faster, then submit pull requests for the issues in the milestone.

> Reading lemmy without filters is hopeless.
> It causes brain rot. We need filters.

For the time being, you could already use the Android app Eternity:
https://codeberg.org/Bazsalanszky/Eternity#readme

It has filter support baked in client side, I wrote a guide on how to use them, on Lemmy:
https://discuss.tchncs.de/post/6091026